WATCHLIST = [
    "RELIANCE","TCS","INFY","HINDUNILVR","ICICIBANK","HDFC","LT","BAJAJFINSV",
    "WIPRO","ASIANPAINT","MARUTI","SBIN","AXISBANK","ITC",
    "SUNPHARMA","LTTS",
    "HCLTECH","TECHM","NESTLEIND",
    "BRITANNIA",
    "DMART",
    "TITAN",
    "ADANIPORTS",
    "GAIL",
    "JSWSTEEL",
    "HEROMOTOCO",
    "BHEL",
    "COALINDIA"
]

CHAT_ID = "7894459956"
SIGNAL_INTERVAL = 1200  # 10 minutes in seconds